joint_limits:
  gripper_finger_joint_r:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: false
    max_acceleration: 0
  arm_joint_3:
    has_velocity_limits: true
    max_velocity: 1.57079632679
    has_acceleration_limits: false
    max_acceleration: 0
  arm_joint_5:
    has_velocity_limits: true
    max_velocity: 1.57079632679
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_finger_joint_l:
    has_velocity_limits: true
    max_velocity: 0.1
    has_acceleration_limits: false
    max_acceleration: 0
  arm_joint_1:
    has_velocity_limits: true
    max_velocity: 1.57079632679
    has_acceleration_limits: false
    max_acceleration: 0
  arm_joint_4:
    has_velocity_limits: true
    max_velocity: 1.57079632679
    has_acceleration_limits: false
    max_acceleration: 0
  arm_joint_2:
    has_velocity_limits: true
    max_velocity: 1.57079632679
    has_acceleration_limits: false
    max_acceleration: 0